# Generated by Django 2.2.1 on 2019-05-02 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190502_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
